package autocode

type ServiceGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleService
	BusInfoService
	GpsInfoService
	RouteInfoService
	LocationInfoService
	ClassesInfoService
	ArrivalInfoService
	ShiftInfoService
	CheckinInfoService
	MilesInfoService
	LocationCommonService
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
