package autocode

type ApiGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleApi
	BusInfoApi
	GpsInfoApi
	RouteInfoApi
	LocationInfoApi
	ClassesInfoApi
	ArrivalInfoApi
	ShiftInfoApi
	CheckinInfoApi
	MilesInfoApi
	LocationCommonApi
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
