package autocode

type RouterGroup struct {
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.
	AutoCodeExampleRouter
	BusInfoRouter
	GpsInfoRouter
	RouteInfoRouter
	LocationInfoRouter
	ClassesInfoRouter
	ArrivalInfoRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
